DROP TABLE IF EXISTS BOOKS;  
CREATE TABLE BOOKS (  
BOOKID INT AUTO_INCREMENT  PRIMARY KEY, 
TITLE VARCHAR(50) NOT NULL,  
AUTHOR VARCHAR(50) NOT NULL,  
PUBLISHER VARCHAR(50) NOT NULL,  
PAGECOUNT INT(8) NOT NULL,
STATUS VARCHAR(50) NOT NULL
);  

DROP TABLE IF EXISTS DVDS;  
CREATE TABLE DVDS (  
DVDID INT AUTO_INCREMENT  PRIMARY KEY, 
TITLE VARCHAR(50) NOT NULL,  
SIZE VARCHAR(50) NOT NULL,
YEAR INT(8) NOT NULL,
STATUS VARCHAR(50) NOT NULL
);